steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - '--destination=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:latest'
      - '--dockerfile=deploy/docker/Dockerfile'
      - '--context=dir:///workspace'
      - '--cache=true'
      - '--cache-ttl=168h'
      - '--snapshot-mode=redo'
      - '--use-new-run'
substitutions:
  _IMAGE_NAME: floportop-v2
options:
  machineType: 'E2_HIGHCPU_8'
